# Site settings
baseurl = "https://example.com"
languageCode = "en-us"
sectionPagesMenu = "main"

[params]
	name = "Frances Hodgkins"
	description = "Landscape and still-life painter from New Zealand"
	email = "frances@hodgkins.io"
	author = "Frances Hodgkins"